### ISSUE TITLE
ValueError: threshold must be non-NAN

### ISSUE THREAD

**Issue by MrLassagna** [jymsuper/SpeakerRecognition_tutorial#2]
python3 SpeakerRecognition_tutorial/identification.py

Traceback (most recent call last):
  File "SpeakerRecognition_tutorial/identification.py", line 10, in <module>
    from DB_wav_reader import read_feats_structure
  File "/content/SpeakerRecognition_tutorial/DB_wav_reader.py", line 11, in <module>
    np.set_printoptions(threshold=np.nan)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/arrayprint.py", line 259, in set_printoptions
    floatmode, legacy)
  File "/usr/local/lib/python3.6/dist-packages/numpy/core/arrayprint.py", line 95, in _make_options_dict
    raise ValueError("threshold must be non-NAN, try "
ValueError: threshold must be non-NAN,

**Comment by jymsuper** [comment]
Please remove the line 20 (np.set_printoptions(threshold=np.nan)) in DB_wav_reader.py file.
